# Generated by Django 6.0.2 on 2026-04-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoo',
            options={'ordering': ['completed', '-priority', '-data']},
        ),
        migrations.AddField(
            model_name='todoo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='todoo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoo',
            name='label',
            field=models.CharField(blank=True, choices=[('', 'None'), ('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent'), ('health', 'Health'), ('finance', 'Finance')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='todoo',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4),
        ),
        migrations.AddField(
            model_name='todoo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.todoo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
